name = "RLToolkit"
uuid = "37971928-86e1-4569-95d0-c97b2346e68c"
authors = ["Matthew Schlegel <mkschleg@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
